# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
