# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170423_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='member',
            name='biography',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='member',
            name='hide_email',
            field=models.BooleanField(choices=[('PRIVATE', False), ('PUBLIC', True)], default=True, verbose_name='Hide email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='hide_phone',
            field=models.BooleanField(choices=[('PRIVATE', False), ('PUBLIC', True)], default=True, verbose_name='Hide phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_accessibility',
            field=models.BooleanField(choices=[('PRIVATE', False), ('PUBLIC', True)], default=True, verbose_name='Hide account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
    ]
