# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170423_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email_accessibility',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_accessibility',
        ),
        migrations.AddField(
            model_name='member',
            name='contact_accessibility',
            field=models.BooleanField(choices=[(False, 'PRIVATE'), (True, 'PUBLIC')], default=True, verbose_name='Contact Accessibility'),
            preserve_default=False,
        ),
    ]
